# Generated by Django 4.2.6 on 2023-10-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('trainee', 'Trainee'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('architect', 'Software Architect'), ('tech_lead', 'Tech Lead')], max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
